name: pelaporan_bencana
description: BPBD.

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=2.17.5 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.2
    font_awesome_flutter: ^10.1.0
    flutter_rating_bar: ^4.0.1
    intl: ^0.19.0
    animations: ^2.0.3
    lottie: ^3.1.0
    flutter_neumorphic:
        git:
            url: https://github.com/den0206/Flutter-Neumorphic.git
            ref: feature/remoce_accentcolor
    geolocator: ^11.0.0
    geocoding: ^3.0.0
    flutter_svg: ^2.0.10+1
    flutter_hooks: ^0.20.5
    firebase_core: ^2.28.0
    image_picker: ^1.0.7
    firebase_auth: ^4.19.2
    telephony: ^0.2.0
    google_maps_flutter: 2.6.1
    permission_handler: ^11.3.1
    firebase_database: ^10.5.0
    cloud_firestore: ^4.17.0
    shared_preferences: ^2.2.3
    firebase_storage: ^11.7.4

dev_dependencies:
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true
    assets:
        - assets/pelaporan_app/
        - assets/introduction_animation/
        - assets/animation/
        - assets/pelaporan_app/login.png
    fonts:
        - family: WorkSans
          fonts:
              - asset: assets/fonts/WorkSans-Regular.ttf
              - asset: assets/fonts/WorkSans-Medium.ttf
                weight: 500
              - asset: assets/fonts/WorkSans-SemiBold.ttf
                weight: 600
              - asset: assets/fonts/WorkSans-Bold.ttf
                weight: 700
        - family: Roboto
          fonts:
              - asset: assets/fonts/Roboto-Bold.ttf
              - asset: assets/fonts/Roboto-Regular.ttf
              - asset: assets/fonts/Roboto-Medium.ttf
                weight: 400
