name: pelaporan_bencana
description: BPBD.

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=2.17.5 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.2
    font_awesome_flutter: ^10.1.0
    flutter_rating_bar: ^4.0.1
    intl: ^0.17.0
    animations: ^2.0.3
    lottie: ^3.1.0
    flutter_neumorphic:
        git:
            url: https://github.com/den0206/Flutter-Neumorphic.git
            ref: feature/remoce_accentcolor
    geolocator: ^11.0.0
    geocoding: ^3.0.0
    flutter_svg: ^2.0.10+1
    flutter_hooks: ^0.20.5
    image_picker: ^0.8.4+4

dev_dependencies:
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true
    assets:
        - assets/pelaporan_app/
        - assets/introduction_animation/
        - assets/animation/
    fonts:
        - family: WorkSans
          fonts:
              - asset: assets/fonts/WorkSans-Regular.ttf
              - asset: assets/fonts/WorkSans-Medium.ttf
                weight: 500
              - asset: assets/fonts/WorkSans-SemiBold.ttf
                weight: 600
              - asset: assets/fonts/WorkSans-Bold.ttf
                weight: 700
        - family: Roboto
          fonts:
              - asset: assets/fonts/Roboto-Bold.ttf
              - asset: assets/fonts/Roboto-Regular.ttf
              - asset: assets/fonts/Roboto-Medium.ttf
                weight: 400
